service: crud-services

provider:
  name: aws
  runtime: nodejs20.x
  iam:
    role:
      statements:
        - Effect: Allow
          Action: 'dynamodb:*'
          Resource: !GetAtt usersTable.Arn

plugins:
  - serverless-esbuild
  - serverless-offline
  - serverless-dynamodb

package:
  exclude:
    - .env/**
    - node_modules/**
    - .github/**

custom:
  esbuild:
    minify: true
    external:
      - aws-sdk
    watch:
      pattern: ['./index.ts', 'src/**/*.ts']
      ignore: ['.serverless/**/*', '.build']
  dynamodb:
    # If you only want to use DynamoDB Local in some stages, declare them here
    stages:
      - dev
    start:
      port: 8000
      inMemory: true
      migrate: true

functions:
  hello-world:
    handler: src/functions/handler.handler
    events:
      - http:
          path: hello-world
          method: GET

  find-user-id:
    handler: src/functions/users/find-id.getUser
    events:
      - http:
          path: users/{id}
          method: GET
  get-users:
    handler: src/functions/users/get.getUsers
    events:
      - http:
          path: users
          method: GET
  create-users:
    handler: src/functions/users/create.createUsers
    events:
      - http:
          path: users
          method: POST
  update-users:
    handler: src/functions/users/update.updateUsers
    events:
      - http:
          path: users/{id}
          method: PUT
  delete-users:
    handler: src/functions/users/delete.deleteUsers
    events:
      - http:
          path: users/{id}
          method: DELETE

resources:
  Resources:
    usersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: users
        AttributeDefinitions:
          - AttributeName: pk
            AttributeType: S
        KeySchema:
          - AttributeName: pk
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
